name: Test and deploy

on:
  push:
    tags:
      - ".*\.-beta$"

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Print tag name
        run: |
          echo ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
          echo ${{ env.PRE_RELEASE }}
#      - name: Tag name
#        id: tag_name
#        run: |
#          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/*/}
#
#      - name: Build base image
#        run: |
#          echo $TAG_NAME
#          git status
#          git checkout master
#          git checkout $TAG_NAME
#          git checkout -b test_branch
#          git status
#          git branch --contains $(git rev-list -n 1 $TAG_NAME)
#          git status
#          git branch -a
#        env:
#          TAG_NAME: ${{ steps.tag_name.outputs.TAG_NAME }}


#  android_tests:
#    runs-on: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
